FROM node:21.2-bookworm

WORKDIR /app

COPY package*.json ./

RUN npm set strict-ssl false

RUN npm install

COPY . .

RUN npm run build

EXPOSE 5173

# Use production-grade servers like nginx to serve frontend
CMD ["npm", "run", "preview"]
